pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'Java-17'
    }

    stages {
        stage('Build & Package') {
            steps {
                dir('Backend/Intervention/Intervention') {
                    echo 'Building Intervention Service JAR...'
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Dockerize') {
            steps {
                dir('Backend/Intervention/Intervention') {
                    echo 'Building Intervention Service Docker image...'
                    sh 'docker build -t intervention-service:latest .'
                }
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                dir('Backend/Intervention/Intervention') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=alzheimer-care-intervention \
                            -Dsonar.projectName="Intervention Service" \
                            -Dsonar.sources=. \
                            -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // 1. Stop and remove the old container
                    sh 'docker stop intervention-service || true'
                    sh 'docker rm intervention-service || true'
                    
                    // 2. Run the new one on the shared network
                    sh """
                        docker run -d --name intervention-service \
                        --network alzheimer-net \
                        -p 8086:8086 \
                        -e SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Intervention \
                        -e EUREKA_SERVER_URL=http://eureka-server:8761/eureka \
                        intervention-service:latest
                    """
                }
            }
        }
    }
}