spring.application.name=AGENDA-MEDICAL
server.port=8101

# --- PostgreSQL ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/agendamedical}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Google Calendar (optionnel)
google.calendar.enabled=${GOOGLE_CALENDAR_ENABLED:false}
google.calendar.credentials-file=${GOOGLE_CALENDAR_CREDENTIALS_FILE:classpath:credentials.json}
google.calendar.tokens-directory=${GOOGLE_CALENDAR_TOKENS_DIRECTORY:tokens}
google.calendar.application-name=${GOOGLE_CALENDAR_APPLICATION_NAME:Projet PI Agenda Medical}
google.calendar.calendar-id=${GOOGLE_CALENDAR_CALENDAR_ID:primary}

# Daily.co Video API
daily.api.key=${DAILY_API_KEY:f8f8c86d4e22f4f693abb4d5ccdd28ac5fb8c18322af560be25dbaaa5af7d5b5}
daily.api.url=${DAILY_API_URL:https://api.daily.co/v1}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}

management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true

springdoc.api-docs.path=/agenda/v3/api-docs
