pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'Java-17'
    }

    stages {
        stage('Build & Package') {
            steps {
                // We DO need to step into the folder so Maven can find the pom.xml!
                dir('Backend/User/User') {
                    echo 'Building User Service JAR...'
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Dockerize') {
            steps {
                // Docker also needs to be in this folder to find the Dockerfile
                dir('Backend/User/User') {
                    echo 'Building User Service Docker image...'
                    sh 'docker build -t user-service:latest .'
                }
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                // SonarQube needs to be in the folder to find the compiled classes
                dir('Backend/User/User') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=alzheimer-care-user-service \
                            -Dsonar.projectName="User Service" \
                            -Dsonar.sources=. \
                            -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // 1. Stop the old user service
                    sh 'docker stop user-service || true'
                    
                    // 2. Remove the old user service
                    sh 'docker rm user-service || true'
                    
                    // 3. Run the new user service and inject the environment variables
                    sh """
                        docker run -d --name user-service \
                        --network alzheimer-net \
                        -p 8082:8082 \
                        -e SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/User \
                        -e EUREKA_SERVER_URL=http://eureka-server:8761/eureka \
                        -e RABBITMQ_HOST=rabbitmq \
                        -e FACE_SERVICE_URL=http://face-service:8000 \
                        user-service:latest
                    """
                }
            }
        }
    }
}