pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'Java-17'
    }

    stages {
        stage('Build & Package') {
            steps {
                // We DO need to step into the folder so Maven can find the pom.xml!
                dir('Backend/User/User') {
                    echo 'Building User Service JAR...'
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Dockerize') {
            steps {
                // Docker also needs to be in this folder to find the Dockerfile
                dir('Backend/User/User') {
                    echo 'Building User Service Docker image...'
                    sh 'docker build -t user-service:latest .'
                }
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                // SonarQube needs to be in the folder to find the compiled classes
                dir('Backend/User/User') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=alzheimer-care-user-service \
                            -Dsonar.projectName="User Service" \
                            -Dsonar.sources=. \
                            -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }
    }
}