pipeline {
    agent any

    tools {
        // Use the exact Node name you saved in Manage Jenkins > Tools
        nodejs 'Node-18' 
    }

    stages {
        stage('Build Frontend') {
            steps {
                dir('Frontend/alzheimer-care-web') {
                    echo 'Installing dependencies...'
                    sh 'npm install --legacy-peer-deps'
                    
                    echo 'Building Angular app...'
                    sh 'npm run build'
                }
            }
        }
        

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                dir('Frontend/alzheimer-care-web') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=alzheimer-care-frontend \
                            -Dsonar.projectName="Angular Frontend" \
                            -Dsonar.sources=src \
                            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
                        """
                    }
                }
            }
        }
        
        stage('Dockerize & Push') {
            steps {
                dir('Frontend/alzheimer-care-web') {
                    // Load the Docker Hub credentials
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        
                        echo 'Logging into Docker Hub...'
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                        
                        echo 'Building image for Docker Hub...'
                        sh 'docker build -t azizesp/evermind-frontend:latest .'
                        
                        echo 'Pushing to Docker Hub...'
                        sh 'docker push azizesp/evermind-frontend:latest'
                    }
                }
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                dir('Frontend/alzheimer-care-web') {
                    echo 'Applying Kubernetes configuration...'
                    sh 'kubectl apply -f k8s-deployment.yaml'
                    
                    echo 'Restarting pods to pull fresh image...'
                    sh 'kubectl rollout restart deployment evermind-frontend'
                }
            }
        }
    }
}