pipeline {
    agent any

    tools {
        // Use the exact Node name you saved in Manage Jenkins > Tools
        nodejs 'Node-18' 
    }

    stages {
        stage('Build Frontend') {
            steps {
                dir('Frontend/alzheimer-care-web') {
                    echo 'Installing dependencies...'
                    sh 'npm install --legacy-peer-deps'
                    
                    echo 'Building Angular app...'
                    sh 'npm run build'
                }
            }
        }
        
        stage('Dockerize') {
            steps {
                dir('Frontend/alzheimer-care-web') {
                    echo 'Building Angular Docker image...'
                    sh 'docker build -t alzheimer-care-web:latest .'
                }
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                dir('Frontend/alzheimer-care-web') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=alzheimer-care-frontend \
                            -Dsonar.projectName="Angular Frontend" \
                            -Dsonar.sources=src \
                            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
                        """
                    }
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    // 1. Stop and remove the old frontend container
                    sh 'docker stop evermind-frontend || true'
                    sh 'docker rm evermind-frontend || true'
                    
                    // 2. Run the new frontend using the image you built above
                    sh """
                        docker run -d --name evermind-frontend \
                        --network alzheimer-net \
                        -p 4200:4000 \
                        alzheimer-care-web:latest
                    """
                }
            }
        }
    }
}