pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'Java-17'
    }

    stages {
        stage('Build & Package') {
            steps {
                dir('Backend/Alert/Alert') {
                    echo 'Building Alert Service JAR...'
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Dockerize') {
            steps {
                dir('Backend/Alert/Alert') {
                    echo 'Building Alert Service Docker image...'
                    sh 'docker build -t alert-service:latest .'
                }
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                dir('Backend/Alert/Alert') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=alzheimer-care-alert \
                            -Dsonar.projectName="Alert Service" \
                            -Dsonar.sources=. \
                            -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // 1. Stop and remove the old container
                    sh 'docker stop alert-service || true'
                    sh 'docker rm alert-service || true'
                    
                    // 2. Run the new one on the shared network
                    sh """
                        docker run -d --name alert-service \
                        --network alzheimer-net \
                        -p 8081:8081 \
                        -e SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Alert \
                        -e EUREKA_SERVER_URL=http://eureka-server:8761/eureka \
                        alert-service:latest
                    """
                }
            }
        }
    }
}