pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'Java-17'
    }

    stages {
        stage('Build & Package') {
            steps {
                dir('Backend/Eureka/EurekaServer') {
                    echo 'Building Eureka Server JAR...'
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                dir('Backend/Eureka/EurekaServer') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=alzheimer-care-eureka \
                            -Dsonar.projectName="Eureka Server" \
                            -Dsonar.sources=. \
                            -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }
        stage('Dockerize & Push') {
            steps {
                dir('Backend/Eureka/EurekaServer') {
                    // Load your Docker Hub credentials
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        
                        echo 'Logging into Docker Hub...'
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                        
                        echo 'Building image for Docker Hub...'
                        sh 'docker build -t azizesp/evermind-eureka:latest .'
                        
                        echo 'Pushing to Docker Hub...'
                        sh 'docker push azizesp/evermind-eureka:latest'
                    }
                }
            }
        }
        stage('Diagnose') {
    steps {
        sh '''
            whoami
            echo HOME=$HOME
            ls -la /home/azureuser/.kube/config || echo "File not found"
            ls -la $HOME/.kube/config || echo "No config in home"
        '''
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                dir('Backend/Eureka/EurekaServer') {
                    echo 'Applying Kubernetes configuration...'
                    sh 'kubectl apply -f k8s-deployment.yaml --kubeconfig=$HOME/.kube/config'
                    
                    echo 'Restarting pods to pull fresh image...'
                    sh 'kubectl rollout restart deployment evermind-eureka'
                }
            }
        }



    }
}