server:
  port: 8090

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          # ✅ CORS under correct prefix
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:4200"
                  - "http://localhost:4201"
                  - "http://20.91.198.213:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    urlsPrimaryName: Alert Service
    urls:
      - name: Alert Service
        url: /alert/v3/api-docs
      - name: Agenda Medical Service
        url: /agenda/v3/api-docs
      - name: Autonomy Service
        url: /autonomy/v3/api-docs
      - name: Cognitive Assessment Service
        url: /cognitive/v3/api-docs
      - name: Conversation Service
        url: /conversation/v3/api-docs
      - name: Intervention Service
        url: /intervention/v3/api-docs
      - name: Patient Service
        url: /patient/v3/api-docs
      - name: Product Service
        url: /product/v3/api-docs
      - name: Profile Service
        url: /profile/v3/api-docs
      - name: Sensor Simulator
        url: /simulation/v3/api-docs
      - name: Stock Service
        url: /stock/v3/api-docs
      - name: User Service
        url: /user/v3/api-docs
      - name: Chatbot Service
        url: /chatbot/v3/api-docs
