pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'Java-17'
    }

    stages {
        stage('Build & Package') {
            steps {
                dir('Backend/SensorSimulator') {
                    echo 'Building Sensor Simulator JAR...'
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Dockerize') {
            steps {
                dir('Backend/SensorSimulator') {
                    echo 'Building Sensor Simulator Docker image...'
                    sh 'docker build -t sensor-simulator:latest .'
                }
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                dir('Backend/SensorSimulator') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=alzheimer-care-sensor-simulator \
                            -Dsonar.projectName="Sensor Simulator Service" \
                            -Dsonar.sources=. \
                            -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // 1. Stop and remove the old container
                    sh 'docker stop sensor-simulator || true'
                    sh 'docker rm sensor-simulator || true'
                    
                    // 2. Run the new one on the shared network
                    sh """
                        docker run -d --name sensor-simulator \
                        --network alzheimer-net \
                        -p 8089:8089 \
                        -e SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/SensorSimulator \
                        -e EUREKA_SERVER_URL=http://eureka-server:8761/eureka \
                        sensor-simulator:latest
                    """
                }
            }
        }
    }
}