pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'Java-17'
    }

    stages {
        stage('Build & Package') {
            steps {
                dir('Backend/Gateway') {
                    echo 'Building API Gateway JAR...'
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Dockerize') {
            steps {
                dir('Backend/Gateway') {
                    echo 'Building API Gateway Docker image...'
                    sh 'docker build -t api-gateway:latest .'
                }
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                dir('Backend/Gateway') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=alzheimer-care-gateway \
                            -Dsonar.projectName="API Gateway" \
                            -Dsonar.sources=. \
                            -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // 1. Stop the old gateway
                    sh 'docker stop api-gateway || true'
                    
                    // 2. Remove the old gateway
                    sh 'docker rm api-gateway || true'
                    
                    // 3. Run the new gateway with the Eureka Environment Variable
                    sh 'docker run -d --name api-gateway --network alzheimer-net -p 8090:8090 -e EUREKA_SERVER_URL=http://eureka-server:8761/eureka api-gateway:latest'
                }
            }
        }
    }
}