pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'Java-17'
    }

    stages {
        stage('Build & Package') {
            steps {
                dir('Backend/Gateway') {
                    echo 'Building API Gateway JAR...'
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarScanner'
            }
            steps {
                dir('Backend/Gateway') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=alzheimer-care-gateway \
                            -Dsonar.projectName="API Gateway" \
                            -Dsonar.sources=. \
                            -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }
        stage('Dockerize & Push') {
            steps {
                dir('Backend/Gateway') {
                    // Load your Docker Hub credentials
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        
                        echo 'Logging into Docker Hub...'
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                        
                        echo 'Building image for Docker Hub...'
                        sh 'docker build -t azizesp/evermind-gateway:latest .'
                        
                        echo 'Pushing to Docker Hub...'
                        sh 'docker push azizesp/evermind-gateway:latest'
                    }
                }
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                dir('Backend/Gateway') {
                    echo 'Applying Kubernetes configuration...'
                    sh 'kubectl apply -f k8s-deployment.yaml'
                    
                    echo 'Restarting pods to pull fresh image...'
                    sh 'kubectl rollout restart deployment evermind-gateway'
                }
            }
        }
    }
}