# Serveur
server.port=8080

# --- PostgreSQL ---
spring.datasource.url=${AGENDA_DB_URL:jdbc:postgresql://localhost:5432/agendamedical}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${AGENDA_DB_USERNAME:postgres}
spring.datasource.password=${AGENDA_DB_PASSWORD:1303}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Google Calendar (optionnel)
google.calendar.credentials-file=${GOOGLE_CALENDAR_CREDENTIALS_FILE:classpath:credentials.json}
google.calendar.tokens-directory=${GOOGLE_CALENDAR_TOKENS_DIRECTORY:tokens}
google.calendar.application-name=${GOOGLE_CALENDAR_APPLICATION_NAME:Projet PI Agenda Medical}
google.calendar.calendar-id=${GOOGLE_CALENDAR_CALENDAR_ID:primary}
